FROM rocker/shiny
RUN R -e "install.packages(c('shiny', 'shinymanager', 'quantmod', 'PerformanceAnalytics', 'tseries', 'rugarch'), repos='https://cran.rstudio.com/')"
COPY /app/ /srv/shiny-server/
